joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  wheel_separation : 0.28
  wheel_radius : 0.041

  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  cmd_vel_timeout: 1.0
    
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.5  # m/s
      min_velocity           : -1.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.0  # m/s^2
      min_acceleration       : -1.0 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.5  # rad/s
      min_velocity           : -1.5
      has_acceleration_limits: true
      max_acceleration       : 2.0  # rad/s^2
      min_acceleration       : -2.0
